export const CLASS_LEVEL = {
    "84": "Class 1",
    "85": "Class 2",
    "86": "Class 3",
    "87": "Class 4",
    "88": "Class 5",
    "89": "Class 6",
    "30": "Maiden Races",
    "4": "Open Handicap",
    "54": "Special Handicap",
    "53": "Set Weights plus Penalties",
    "198": "Benchmark 50",
    "199": "Benchmark 55",
    "226": "Benchmark 58",
    "200": "Benchmark 60",
    "231": "Benchmark 64",
    "232": "Benchmark 66",
    "234": "Benchmark 68",
    "202": "Benchmark 70",
    "238": "Benchmark 74",
    "203": "Benchmark 75",
    "241": "Benchmark 78",
    "204": "Benchmark 80",
    "205": "Benchmark 85",
    "206": "Benchmark 90",
    "207": "Benchmark 95",
    "208": "Benchmark 100",
}

export const START_FILTER_CNT = {
    "Last 10": 10,
    "Last 20": 20,
    "Last 50": 50,
    "Last 100": 100,
    "Last 200": 200,
    "Last 500": 500,
    "Last 1000": 1000,
    "Last 2000": 2000,
    "Last 5000": 5000,
}

export const TRACKS = {
    "Australia": {
        "METRO": [
            "RANDWICK",
            "RANDWICK-KENSINGTON",
            "ROSEHILL",
            "WARWICK FARM",
            "CANTERBURY",
            "FLEMINGTON",
            "CAULFIELD",
            "MOONEE VALLEY",
            "SANDOWN HILLSIDE",
            "SANDOWN LAKESIDE",
            "EAGLE FARM",
            "DOOMBEN",
            "MORPHETTVILLE",
            "ASCOT",
            "BELMONT",
            "DARWIN",
            "CANBERRA",
            "HOBART",
            "LAUNCESTON"
        ],
        "PROVINCIAL": [
            "HAWKESBURY",
            "GOSFORD",
            "WYONG",
            "NEWCASTLE",
            "KEMBLA GRANGE",
            "GEELONG",
            "MORNINGTON",
            "BALLARAT",
            "BENDIGO",
            "CRANBOURNE",
            "PAKENHAM",
            "SEYMOUR",
            "WERRIBEE",
            "GOLD COAST",
            "SUNSHINE COAST",
            "IPSWICH",
            "TOOWOOMBA",
            "MURRAY BRIDGE",
            "GAWLER",
            "OAKBANK",
            "BUNBURY",
            "PINJARRA",
            "ALBANY",
            "NORTHAM",
            "GERALDTON",
            "ALICE SPRINGS",
            "DEVONPORT"
        ],
        "COUNTRY": [
            "ALBURY",
            "ARMIDALE",
            "BALLINA",
            "BATHURST",
            "BEGA",
            "CESSNOCK",
            "COFFS HARBOUR",
            "DUBBO",
            "GOULBURN",
            "GRAFTON",
            "INVERELL",
            "LISMORE",
            "MUDGEE",
            "MURWILLUMBAH",
            "MUSWELLBROOK",
            "ORANGE",
            "PARKES",
            "QUEANBEYAN",
            "SCONE",
            "TAMWORTH",
            "TAREE",
            "WAGGA WAGGA",
            "WARRNAMBOOL",
            "WANGARATTA",
            "SALE",
            "ECHUCA",
            "SWAN HILL",
            "HAMILTON",
            "HORSHAM",
            "BAIRNSDALE",
            "COLAC",
            "WODONGA",
            "CAIRNS",
            "TOWNSVILLE",
            "MACKAY",
            "ROCKHAMPTON",
            "BUNDABERG",
            "ROMA",
            "WARWICK",
            "GATTON",
            "MOUNT GAMBIER",
            "PORT LINCOLN",
            "PORT AUGUSTA",
            "PENOLA",
            "STRATHALBYN",
            "MORPHETTVILLE",
            "BALAKLAVA",
            "NARACOORTE",
            "BROOME",
            "KALGOORLIE",
            "ESPERANCE BAY",
            "NARROGIN",
            "YORK",
            "KATHERINE",
            "TENNANT CREEK",
            "PIONEER PARK",
            "LONGFORD",
            "CARRICK"
        ]
    },
    "New South Wales": {
        "METRO": [
            "RANDWICK",
            "ROSEHILL",
            "WARWICK FARM",
            "CANTERBURY"
        ],
        "PROVINCIAL": [
            "HAWKESBURY",
            "GOSFORD",
            "WYONG",
            "NEWCASTLE",
            "KEMBLA GRANGE"
        ],
        "COUNTRY": [
            "ALBURY",
            "ARMIDALE",
            "BALLINA",
            "BATHURST",
            "BEGA",
            "CESSNOCK",
            "COFFS HARBOUR",
            "DUBBO",
            "GOULBURN",
            "GRAFTON",
            "INVERELL",
            "LISMORE",
            "MUDGEE",
            "MURWILLUMBAH",
            "MUSWELLBROOK",
            "ORANGE",
            "PARKES",
            "QUEANBEYAN",
            "SCONE",
            "TAMWORTH",
            "TAREE",
            "WAGGA WAGGA"
        ]
    },
    "Victoria": {
        "METRO": [
            "FLEMINGTON", "CAULFIELD", "MOONEE VALLEY", ""
        ],
        "PROVINCIAL": [
            "GEELONG", "MORNINGTON", "BALLARAT", "BENDIGO", "CRANBOURNE", "PAKENHAM", "SEYMOUR", "WERRIBEE"
        ],
        "COUNTRY": [
            "WARRNAMBOOL", "WANGARATTA", "SALE", "ECHUCA", "SWAN HILL", "HAMILTON", "HORSHAM", "BAIRNSDALE", "COLAC", "WODONGA"
        ]
    },
    "Queensland": {
        "METRO": ["EAGLE FARM", "DOOMBEN"],
        "PROVINCIAL": ["GOLD COAST", "SUNSHINE COAST", "IPSWICH", "TOOWOOMBA"],
        "COUNTRY": [
            "CAIRNS",
            "TOWNSVILLE",
            "MACKAY",
            "ROCKHAMPTON",
            "BUNDABERG",
            "ROMA",
            "WARWICK",
            "GATTON"
        ]
    },
    "Northern Territory": {
        "METRO": ["DARWIN"],
        "PROVINCIAL": ["ALICE SPRINGS"],
        "COUNTRY": ["KATHERINE", "TENNANT CREEK", "PIONEER PARK"]
    },
    "Western Australia": {
        "METRO": ["ASCOT", "BELMONT"],
        "PROVINCIAL": ["BUNBURY", "PINJARRA", "ALBANY", "NORTHAM", "GERALDTON"],
        "COUNTRY": ["BROOME", "KALGOORLIE", "ESPERANCE BAY", "Carnarvon", "NARROGIN", "YORK"]
    },
    "South Australia": {
        "METRO": ["MORPHETTVILLE"],
        "PROVINCIAL": ["MURRAY BRIDGE", "GAWLER", "OAKBANK"],
        "COUNTRY": [
            "MOUNT GAMBIER",
            "PORT LINCOLN",
            "PORT AUGUSTA",
            "PENOLA",
            "STRATHALBYN",
            "MORPHETTVILLE",
            "BALAKLAVA",
            "NARACOORTE"
        ]
    },
    "Tasmania": {
        "METRO": ["HOBART", "LAUNCESTON"],
        "PROVINCIAL": ["DEVONPORT"],
        "COUNTRY": ["LONGFORD", "CARRICK"]
    }
}

export const CLASS_POINT = {
    "Maiden": 1,
    "Mdn": 1,
    "Open": 7,
    "Cls 1": 3,
    "Cls 2": 3.5,
    "Cls 3": 4,
    "Cls 4": 4.5,
    "Cls 5": 5,
    "Cls 6": 5.5,
    "Class 1": 3,
    "Class 2": 3.5,
    "Class 3": 4,
    "Class 4": 4.5,
    "Class 5": 5,
    "Class 6": 5.5,
    "BM40": 1.5,
    "BM45": 2,
    "BM50": 2.5,
    "BM55": 3,
    "BM55+": "3+",
    "BM58": 3.3,
    "BM60": 3.5,
    "BM64": 3.8,
    "BM66": 4,
    "BM68": 4.2,
    "BM70": 4.4,
    "BM72": 4.5,
    "BM74": 4.6,
    "BM75": 4.8,
    "BM78": 5,
    "BM80": 5.5,
    "BM85": 6,
    "BM90": 6.5,
    "BM95": 7,
    "BM100": 7.5,
    "Rest": "Rest",
    "RST52": "RST52",
    "RST54": "RST54",
    "RST55": "RST55",
    "RST58": "RST58",
    "RST60": "RST560",
    "RST62": "RST62",
    "RST64": "RST64",
    "RST65": "RST65",
    "RST70": "RST70",
    "RST85": "RST85",
    "RST90": "RST90",
    "RS0LY": "RS0LY",
    "Rs0MW": "Rs0MW",
    "Rs1MW": "Rs1MW",
    "Restricted 58": "Restricted 58",
    "Griff": "Griff",
    "G-Open": "G-Open",
    "Spec": 6,
    "Stpl": "Stpl",
    "Hrdle": "Hrdle",
    "Hurdle": "Hurdle",
    "HiWgt": "HiWgt",
    "JMPFL": "JMPFL",
    "Nov": "Nov",
}